### ISSUE TITLE
Cannot import DejaGnu results from GDB testsuite

### ISSUE THREAD

**Issue by petr-muller** [FilipMatys/ResultCloud#49]
I am not able to import the results from running the GDB testsuite:

When I try to import the file using external python script, I get:
```
$ ./corly-import.py login password 3 2 gdb.sum
Logged in
Start upload: gdb.sum
Part 0: OK
Part 1: OK
Part 2: OK
Not found any file part
```

When I try to import the file manually from the web UI, it is imported incompletely:
http://hele.fit.vutbr.cz/~xmatys10/production/#/home/project/2/submission/44

The result file I am using: http://www.afri.cz/files/gdb.sum

**Comment by petr-muller** [comment]
This does not fully work yet, it gives 500 during the last step.

$ ./corly_import.py <user> <pwd> 3 2 gdb.sum
<Response [200]>
Logged in
<Response [200]>
Start upload: gdb.sum
<Response [200]>
Part 0: OK
<Response [200]>
Part 1: OK
<Response [200]>
Part 2: OK
<Response [500]>
Traceback (most recent call last):
  File "./corly_import.py", line 94, in <module>
    send_test(user_name, password, plugin, project, file_name)
  File "./corly_import.py", line 75, in send_test
    if user.end_upload_session(session_id):
  File "/home/afri/Projects/IBP2013/scripts/corlyapi.py", line 28, in end_upload_session
    resp = self.send_request("import", "end", {"sessionid": session_id})
  File "/home/afri/Projects/IBP2013/scripts/corlyapi.py", line 47, in send_request
    resp = json.loads(resp.text)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by petr-muller** [comment]
Okay, I have found a likely culprit.
When I try to import gdb.sum into an empty project, it works, using both API and WebUI.
When I try to import gdb.sum into a project with a submission already, it does not work (endless wheel spinning in WebUI and 500 in API). So the culprit is likely in the comparison code.

**Comment by petr-muller** [comment]
Current behavior:
```
$ ./corly_import.py muller <.password.> 3 2 ../../binutils-gdb/build/gdb/testsuite/gdb.sum
<Response [200]>
Logged in
<Response [200]>
Start upload: gdb.sum
<Response [200]>
Part 0: OK
<Response [200]>
Part 1: OK
<Response [200]>
Part 2: OK
<Response [200]>
Not found any file part
```
with a slightly modified corlyapi.py:
```diff
diff --git a/scripts/corlyapi.py b/scripts/corlyapi.py
index 1ec14e5..2ff784d 100755
--- a/scripts/corlyapi.py
+++ b/scripts/corlyapi.py
@@ -5,7 +5,7 @@ import requests
 
 
 class CorlyAPI:
-    URL = "http://corly.com/method/"
+    URL = "http://www.result-cloud.org/production/method/"
     token = ""
     isValid = False
     errors = list()
@@ -42,14 +42,19 @@ class CorlyAPI:
         str_values = "&".join(["%s=%s" % (k, v) for k, v in params.items()])
         request = "%s%s.%s?%s" % (self.URL, method, function, str_values)
 
-        resp = json.loads(requests.get(request).text)
+	resp = requests.get(request)
+	print resp
+        resp = json.loads(resp.text)
         return resp
 
+
     def send_file(self, params, filename):
         str_values = "&".join(["%s=%s" % (k, v) for k, v in params.items()])
         files = {'file': open(filename, 'rb')}
         request = "%simport.upload?%s" % (self.URL, str_values)
-        resp = requests.post(request, files=files).json()
+        resp = requests.post(request, files=files)
+	print resp
+	resp = resp.json()
 
         return resp
```

**Comment by FilipMatys** [comment]
@bond95 
Did you solve the issue before, when there was a problem with creating the temp directory? Same problem now, GUI import works, but import for big files is still an issue.

**Comment by FilipMatys** [comment]
Managed to upload big file via script creating temp folder manually, but I consider this as s workaround. Suggest allowing Apache to create files/folders or using different approach to upload big files.

**Comment by bond95** [comment]
yes, i solved this problem, it must upload to the standard temp directory /tmp

**Comment by FilipMatys** [comment]
Ok, fixed it.

**Comment by petr-muller** [comment]
It looks fixed, my automated job uploaded some results:
http://result-cloud.org/production/#/project/2

**Comment by petr-muller** [comment]
Fixed.
